### ISSUE TITLE
Screenshot isn't showing anymore

### ISSUE THREAD

**Issue by Snailedlt** [ez4o/github-contribution-graph#2]
https://github.com/ez4o/github-contribution-graph#about-the-project
![image](https://user-images.githubusercontent.com/43886029/167954122-fe44013a-9ca2-422d-87c8-87c379aea85c.png)

**Comment by wst24365888** [comment]
Thanks for your report. Working on it!

**Comment by Snailedlt** [comment]
Amazing responsetime!
I'm considering using this for my profile now :)
